# ~/.bash_aliases - Aliases definitions

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias lsd='ls -d */'

alias cd..='cd ..'
alias ..='cd ..'
alias du='du -h'
alias df='df -h'
